# @host = http://localhost:8080
@host = http://192.168.0.103:8080
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjViM2VjNzkxZTQ0NGZkMzFkNTZhMWIyIiwiaWF0IjoxNzA2NjQ0MjAzLCJleHAiOjE3MDY2ODAyMDN9.LoKmFqgfRbZiAMbDOWYTfsgSp5AZbTkSVewY4iUi5oE

### ! /
GET {{host}} HTTP/1.1


### ! Get User
GET {{host}}/api/login HTTP/1.1
content-type: application/json
x-auth-token: {{token}}


### ! Login
POST {{host}}/api/login HTTP/1.1
content-type: application/json

{
    "email": "r@g.com",
    "password": "sadd"
}

### ! Sign Up
POST {{host}}/api/signup HTTP/1.1
content-type: application/json

{
    "name": "Red",
    "email": "r@g.com",
    "password": "sadd"
}